/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import java.time.LocalDate;
import java.time.Period;
import java.sql.Date;
import java.sql.*;
import conexion.conexionSQL;
import java.sql.Connection;
import conexion.*;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author DELL
 */
public class Antecedentes2 extends javax.swing.JFrame {

    /**
     * Creates new form Antecedentes2
     */
    public Antecedentes2() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Titulo = new javax.swing.JLabel();
        label_cedula = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        boton_buscar = new javax.swing.JButton();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        label_edad = new javax.swing.JLabel();
        label_sexo = new javax.swing.JLabel();
        label_gruposanguineo = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        txt_sexo = new javax.swing.JTextField();
        txt_gruposanguineo = new javax.swing.JTextField();
        label_antecedentesmedicos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_antecedentesmedicos = new javax.swing.JTextArea();
        label_enfermedades = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_enfermedades = new javax.swing.JTextArea();
        label_observaciones = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        boton_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 51));

        Label_Titulo.setText("Antecedentes");

        label_cedula.setText("Cedula");

        label_nombre.setText("Nombre");

        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(Label_Titulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(174, 174, 174)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_nombre)
                            .addComponent(label_cedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(txt_nombre))
                        .addGap(18, 18, 18)
                        .addComponent(boton_buscar)))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Label_Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_cedula)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_nombre)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(boton_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addGap(7, 7, 7))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 120));

        jPanel2.setBackground(new java.awt.Color(0, 51, 51));

        label_edad.setText("Edad");

        label_sexo.setText("Sexo");

        label_gruposanguineo.setText("Grupo Sanguineo");

        label_antecedentesmedicos.setText("Antecedentes Medicos");

        txt_antecedentesmedicos.setColumns(20);
        txt_antecedentesmedicos.setRows(5);
        jScrollPane1.setViewportView(txt_antecedentesmedicos);

        label_enfermedades.setText("Enfermedades");

        txt_enfermedades.setColumns(20);
        txt_enfermedades.setRows(5);
        jScrollPane2.setViewportView(txt_enfermedades);

        label_observaciones.setText("observaciones");

        txt_observaciones.setColumns(20);
        txt_observaciones.setRows(5);
        jScrollPane3.setViewportView(txt_observaciones);

        boton_guardar.setText("Guardar");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(245, 245, 245)
                            .addComponent(label_observaciones))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(label_edad)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(label_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(label_gruposanguineo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(label_enfermedades)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_gruposanguineo, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addGap(60, 60, 60))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(label_antecedentesmedicos))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(164, 164, 164)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(boton_guardar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_edad)
                    .addComponent(label_sexo)
                    .addComponent(label_gruposanguineo)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gruposanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_antecedentesmedicos)
                    .addComponent(label_enfermedades))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                        .addComponent(boton_guardar)
                        .addGap(75, 75, 75))))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 600, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
       String cedula = txt_cedula.getText();
        try {
            
            String url= "jdbc:mysql://localhost:3306/medicontrol";
            String usuario =  "medicontrol";
            String pass = "bata31@";
            Connection cn = DriverManager.getConnection(url,usuario,pass);
                    
            
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM paciente WHERE cedula = ?");
            pst.setString(1, cedula);
            ResultSet rs= pst.executeQuery();
             if(rs.next()) {
                txt_nombre.setText(rs.getString("nombre")+rs.getString("apellido"));
                txt_sexo.setText(rs.getString("sexo"));
                txt_gruposanguineo.setText(rs.getString("grupo sanguineo"));
                txt_edad.setText(rs.getString("fecha de nacimiento"));
                
            } else {
                JOptionPane.showMessageDialog(null,"Paciente no encontrado");
            }
            PreparedStatement ps2 = cn.prepareStatement("SELECT cedula, historial, enfermedades, observaciones FROM antecedentes WHERE cedula = ?");
            ps2.setString(1, cedula);
            ResultSet rs2 = ps2.executeQuery();

             if (rs2.next()) {
                txt_antecedentesmedicos.setText(rs2.getString("historial"));
                txt_enfermedades.setText(rs2.getString("enfermedades"));
                txt_observaciones.setText(rs2.getString("observaciones"));
             } else {
                txt_antecedentesmedicos.setText("");
                txt_enfermedades.setText("");
                txt_observaciones.setText("");
}

            
            
                    
            
        } catch (HeadlessException | SQLException e) {
            System.out.println("Error :" +e);
        }
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
    String cedula = txt_cedula.getText().trim();
    String ant_med = txt_antecedentesmedicos.getText().trim();
    String enfermedades = txt_enfermedades.getText().trim();
    String observaciones = txt_observaciones.getText().trim();
        try {
            String url= "jdbc:mysql://localhost:3306/medicontrol";
            String usuario =  "medicontrol";
            String pass = "bata31@";
            Connection cn = DriverManager.getConnection(url,usuario,pass);
            PreparedStatement pst = cn.prepareStatement("Select * from antecedentes where cedula = ?");
            pst.setString(1,cedula);
            ResultSet rs= pst.executeQuery();
            if (rs.next()) {
                PreparedStatement psupdate = cn.prepareStatement("update antecedentes set historial = ?, enfermedades = ?, observaciones = ? WHERE cedula = ?");
                psupdate.setString(1, ant_med);
                psupdate.setString(2, enfermedades);
                psupdate.setString(3, observaciones);
                psupdate.setString(4, cedula);

                psupdate.executeUpdate();
                JOptionPane.showMessageDialog(this, "Informacion actualizada correctamente");
            }else {
                PreparedStatement psInsert = cn.prepareStatement("INSERT INTO antecedentes (id_antecedentes, cedula, historial, enfermedades, observaciones) values (?, ?, ?, ?, ?)");
                psInsert.setInt(1,0);
                psInsert.setString(2,cedula);
                psInsert.setString(3,ant_med);
                psInsert.setString(4,enfermedades);
                psInsert.setString(5,observaciones);
                psInsert.executeUpdate();
                JOptionPane.showMessageDialog(this, "antecedentes guardados correctamente");
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error al guardar: "+e.getMessage());
        }
    
   
             
                
            
            
   
    
    }//GEN-LAST:event_boton_guardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antecedentes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antecedentes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antecedentes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antecedentes2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antecedentes2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Titulo;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_antecedentesmedicos;
    private javax.swing.JLabel label_cedula;
    private javax.swing.JLabel label_edad;
    private javax.swing.JLabel label_enfermedades;
    private javax.swing.JLabel label_gruposanguineo;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_observaciones;
    private javax.swing.JLabel label_sexo;
    private javax.swing.JTextArea txt_antecedentesmedicos;
    public javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextArea txt_enfermedades;
    private javax.swing.JTextField txt_gruposanguineo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextArea txt_observaciones;
    public javax.swing.JTextField txt_sexo;
    // End of variables declaration//GEN-END:variables
}
