/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;
import java.time.LocalDate;
import java.time.Period;
import java.sql.Date;
import java.sql.*;
import conexion.conexionSQL;
import java.sql.Connection;
import conexion.*;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;

/**
 *
 * @author 
 */
public class Antecedentes extends javax.swing.JFrame {

    /**
     * Creates new form Antecedentes
     */
    public Antecedentes() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Label_Titulo = new javax.swing.JLabel();
        label_cedula = new javax.swing.JLabel();
        label_nombre = new javax.swing.JLabel();
        boton_buscar = new javax.swing.JButton();
        txt_cedula = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        Volverbtn = new javax.swing.JToggleButton();
        jPanel2 = new javax.swing.JPanel();
        label_edad = new javax.swing.JLabel();
        label_sexo = new javax.swing.JLabel();
        label_gruposanguineo = new javax.swing.JLabel();
        txt_edad = new javax.swing.JTextField();
        txt_sexo = new javax.swing.JTextField();
        txt_gruposanguineo = new javax.swing.JTextField();
        label_antecedentesmedicos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_antecedentesmedicos = new javax.swing.JTextArea();
        label_enfermedades = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_enfermedades = new javax.swing.JTextArea();
        label_observaciones = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_observaciones = new javax.swing.JTextArea();
        boton_guardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(76, 207, 225));
        jPanel1.setForeground(new java.awt.Color(76, 207, 225));

        Label_Titulo.setBackground(new java.awt.Color(255, 255, 255));
        Label_Titulo.setFont(new java.awt.Font("Verdana", 1, 28)); // NOI18N
        Label_Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Label_Titulo.setText("Antecedentes");

        label_cedula.setBackground(new java.awt.Color(255, 255, 255));
        label_cedula.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        label_cedula.setForeground(new java.awt.Color(255, 255, 255));
        label_cedula.setText("Cedula");

        label_nombre.setBackground(new java.awt.Color(255, 255, 255));
        label_nombre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        label_nombre.setForeground(new java.awt.Color(255, 255, 255));
        label_nombre.setText("Nombre");

        boton_buscar.setBackground(new java.awt.Color(255, 255, 255));
        boton_buscar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_buscar.setForeground(new java.awt.Color(76, 207, 225));
        boton_buscar.setText("Buscar");
        boton_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_buscarActionPerformed(evt);
            }
        });

        txt_cedula.setBackground(new java.awt.Color(255, 255, 255));
        txt_cedula.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_cedula.setForeground(new java.awt.Color(76, 207, 225));

        txt_nombre.setBackground(new java.awt.Color(255, 255, 255));
        txt_nombre.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        txt_nombre.setForeground(new java.awt.Color(76, 207, 225));

        Volverbtn.setBackground(new java.awt.Color(255, 255, 255));
        Volverbtn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Volverbtn.setForeground(new java.awt.Color(76, 207, 225));
        Volverbtn.setText("VOLVER");
        Volverbtn.setBorder(null);
        Volverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(174, 174, 174)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label_nombre)
                            .addComponent(label_cedula))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                            .addComponent(txt_nombre))
                        .addGap(18, 18, 18)
                        .addComponent(boton_buscar)
                        .addContainerGap(147, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Label_Titulo)
                        .addGap(82, 82, 82)
                        .addComponent(Volverbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_Titulo)
                    .addComponent(Volverbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(label_cedula, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_nombre)
                            .addComponent(txt_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(boton_buscar)
                        .addGap(23, 23, 23))))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 120));

        jPanel2.setBackground(new java.awt.Color(177, 234, 242));

        label_edad.setBackground(new java.awt.Color(255, 255, 255));
        label_edad.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label_edad.setForeground(new java.awt.Color(255, 255, 255));
        label_edad.setText("Edad:");

        label_sexo.setBackground(new java.awt.Color(255, 255, 255));
        label_sexo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label_sexo.setForeground(new java.awt.Color(255, 255, 255));
        label_sexo.setText("Sexo:");

        label_gruposanguineo.setBackground(new java.awt.Color(255, 255, 255));
        label_gruposanguineo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label_gruposanguineo.setForeground(new java.awt.Color(255, 255, 255));
        label_gruposanguineo.setText("Grupo Sanguineo:");

        txt_edad.setBackground(new java.awt.Color(255, 255, 255));
        txt_edad.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_edad.setForeground(new java.awt.Color(76, 207, 225));

        txt_sexo.setBackground(new java.awt.Color(255, 255, 255));
        txt_sexo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_sexo.setForeground(new java.awt.Color(76, 207, 225));

        txt_gruposanguineo.setBackground(new java.awt.Color(255, 255, 255));
        txt_gruposanguineo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_gruposanguineo.setForeground(new java.awt.Color(76, 207, 225));

        label_antecedentesmedicos.setBackground(new java.awt.Color(255, 255, 255));
        label_antecedentesmedicos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label_antecedentesmedicos.setForeground(new java.awt.Color(255, 255, 255));
        label_antecedentesmedicos.setText("Antecedentes Medicos");

        txt_antecedentesmedicos.setBackground(new java.awt.Color(255, 255, 255));
        txt_antecedentesmedicos.setColumns(20);
        txt_antecedentesmedicos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_antecedentesmedicos.setForeground(new java.awt.Color(76, 207, 225));
        txt_antecedentesmedicos.setRows(5);
        jScrollPane1.setViewportView(txt_antecedentesmedicos);

        label_enfermedades.setBackground(new java.awt.Color(255, 255, 255));
        label_enfermedades.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label_enfermedades.setForeground(new java.awt.Color(255, 255, 255));
        label_enfermedades.setText("Enfermedades");

        txt_enfermedades.setBackground(new java.awt.Color(255, 255, 255));
        txt_enfermedades.setColumns(20);
        txt_enfermedades.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_enfermedades.setForeground(new java.awt.Color(76, 207, 225));
        txt_enfermedades.setRows(5);
        jScrollPane2.setViewportView(txt_enfermedades);

        label_observaciones.setBackground(new java.awt.Color(255, 255, 255));
        label_observaciones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        label_observaciones.setForeground(new java.awt.Color(255, 255, 255));
        label_observaciones.setText("observaciones");

        txt_observaciones.setBackground(new java.awt.Color(255, 255, 255));
        txt_observaciones.setColumns(20);
        txt_observaciones.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        txt_observaciones.setForeground(new java.awt.Color(76, 207, 225));
        txt_observaciones.setRows(5);
        jScrollPane3.setViewportView(txt_observaciones);

        boton_guardar.setBackground(new java.awt.Color(255, 255, 255));
        boton_guardar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        boton_guardar.setForeground(new java.awt.Color(76, 207, 225));
        boton_guardar.setText("Guardar");
        boton_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(label_edad)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label_antecedentesmedicos)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addComponent(label_sexo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(label_gruposanguineo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_gruposanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(label_enfermedades)
                        .addGap(129, 129, 129))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(180, 180, 180))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(boton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(label_observaciones)
                        .addGap(267, 267, 267))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_edad)
                    .addComponent(label_sexo)
                    .addComponent(label_gruposanguineo)
                    .addComponent(txt_edad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_gruposanguineo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_antecedentesmedicos)
                    .addComponent(label_enfermedades, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(label_observaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(boton_guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 640, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void boton_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_buscarActionPerformed
       
       //Conexion a la base de datos y buscar los datos del paciente segun su cedula
       String cedula = txt_cedula.getText();
        try {
            
            String url= "jdbc:mysql://localhost:3306/medicontrol";
            String usuario =  "medicontrol";
            String pass = "bata31@";
            Connection cn = DriverManager.getConnection(url,usuario,pass);
                    
            //primera solicitud de la base de datos, buscando los datos desde la tabla pacientes segun la cedula
            PreparedStatement pst = cn.prepareStatement("SELECT * FROM paciente WHERE cedula = ?");
            pst.setString(1, cedula);
            ResultSet rs= pst.executeQuery();
             if(rs.next()) {
                txt_nombre.setText(rs.getString("nombre")+ " " + rs.getString("apellido"));
                txt_sexo.setText(rs.getString("sexo"));
                txt_gruposanguineo.setText(rs.getString("grupo sanguineo"));
                 Date fechaNac = rs.getDate("fecha de nacimiento");
                   //Tomar la fecha de nacimiento y convertirla en años para mostrar
                   if (fechaNac != null) {
                      LocalDate nacimiento = fechaNac.toLocalDate();
                      int edad = Period.between(nacimiento, LocalDate.now()).getYears();
                      txt_edad.setText(String.valueOf(edad));
              } else {
                      txt_edad.setText("");
        }
                
            } else {
                JOptionPane.showMessageDialog(null,"Paciente no encontrado");
            }
            //segunda solicitud, pidiendo los datos desde antecedentes segun la cedula
            PreparedStatement ps2 = cn.prepareStatement("SELECT cedula, historial, enfermedades, observaciones FROM antecedentes WHERE cedula = ?");
            ps2.setString(1, cedula);
            ResultSet rs2 = ps2.executeQuery();

             if (rs2.next()) {
                txt_antecedentesmedicos.setText(rs2.getString("historial"));
                txt_enfermedades.setText(rs2.getString("enfermedades"));
                txt_observaciones.setText(rs2.getString("observaciones"));
             } else {
                txt_antecedentesmedicos.setText("");
                txt_enfermedades.setText("");
                txt_observaciones.setText("");
}

            
            
                    
            
        } catch (HeadlessException | SQLException e) {
            System.out.println("Error :" +e);
        }
    }//GEN-LAST:event_boton_buscarActionPerformed

    private void boton_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton_guardarActionPerformed
   
    //Boton para guardar los antecedentes y actualizarlos en caso de querer editarse.
    String cedula = txt_cedula.getText().trim();
    String ant_med = txt_antecedentesmedicos.getText().trim();
    String enfermedades = txt_enfermedades.getText().trim();
    String observaciones = txt_observaciones.getText().trim();
        try {
            //Conexion a la base de datos
            String url= "jdbc:mysql://localhost:3306/medicontrol";
            String usuario =  "medicontrol";
            String pass = "bata31@";
            Connection cn = DriverManager.getConnection(url,usuario,pass);
            //Verificar que la cedula en caso de haber sido cambiada por error, no se retorne si es incorrecta.
            PreparedStatement checkPaciente = cn.prepareStatement("SELECT * FROM paciente WHERE cedula = ?");
            checkPaciente.setString(1, cedula);
            ResultSet resPaciente = checkPaciente.executeQuery();

           if (!resPaciente.next()) {
            JOptionPane.showMessageDialog(this, "Esa cédula no está registrada como paciente. Ingrese la cedula correctamente.");
            return; //salir del método para no insertar nada
           }
           //Actualizacion de los antecedentes
            PreparedStatement pst = cn.prepareStatement("Select * from antecedentes where cedula = ?");
            pst.setString(1,cedula);
            ResultSet rs= pst.executeQuery();
            if (rs.next()) {
                PreparedStatement psupdate = cn.prepareStatement("update antecedentes set historial = ?, enfermedades = ?, observaciones = ? WHERE cedula = ?");
                psupdate.setString(1, ant_med);
                psupdate.setString(2, enfermedades);
                psupdate.setString(3, observaciones);
                psupdate.setString(4, cedula);

                psupdate.executeUpdate();
                JOptionPane.showMessageDialog(this, "Informacion actualizada correctamente");
            }else {
                //Primer guardado de antecedentes (cuando todo esta vacio)
                PreparedStatement psInsert = cn.prepareStatement("INSERT INTO antecedentes (id_antecedentes, cedula, historial, enfermedades, observaciones) values (?, ?, ?, ?, ?)");
                psInsert.setInt(1,0);
                psInsert.setString(2,cedula);
                psInsert.setString(3,ant_med);
                psInsert.setString(4,enfermedades);
                psInsert.setString(5,observaciones);
                psInsert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Antecedentes guardados correctamente");
            }
        } catch (Exception e) {
             JOptionPane.showMessageDialog(this, "Error al guardar: "+e.getMessage());
        }
    
   
             
                
            
            
   
    
    }//GEN-LAST:event_boton_guardarActionPerformed

    private void VolverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverbtnActionPerformed
       
        //Boton para volver al menu principal
        Menu_Principal mp = new Menu_Principal();
        this.dispose();
        mp.setVisible(true);
        mp.pack();
        mp.setLocationRelativeTo(null);
    }//GEN-LAST:event_VolverbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Antecedentes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Antecedentes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Label_Titulo;
    public javax.swing.JToggleButton Volverbtn;
    private javax.swing.JButton boton_buscar;
    private javax.swing.JButton boton_guardar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel label_antecedentesmedicos;
    private javax.swing.JLabel label_cedula;
    private javax.swing.JLabel label_edad;
    private javax.swing.JLabel label_enfermedades;
    private javax.swing.JLabel label_gruposanguineo;
    private javax.swing.JLabel label_nombre;
    private javax.swing.JLabel label_observaciones;
    private javax.swing.JLabel label_sexo;
    private javax.swing.JTextArea txt_antecedentesmedicos;
    public javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_edad;
    private javax.swing.JTextArea txt_enfermedades;
    private javax.swing.JTextField txt_gruposanguineo;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextArea txt_observaciones;
    public javax.swing.JTextField txt_sexo;
    // End of variables declaration//GEN-END:variables
}
