package Interfaces;

import conexion.*;
import java.sql.Connection;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

public class listaPacientes extends javax.swing.JFrame {
    
    conexionSQL con = new conexionSQL();
    Connection cn = con.conectar();

    
    public listaPacientes() {
        initComponents();
        cargarPacientesEnTabla();
    }
    
    private void cargarPacientesEnTabla() {
        DAOPacientes dao = new DAOPacientes(cn);
        List<Pacientes> lista = dao.obtenerTodosLosPacientes();

        // Asegurar que el modelo tenga las columnas correctas
        DefaultTableModel modelo = new DefaultTableModel(new String[] { "Cédula", "Nombre", "Apellido", "Teléfono" }, 0);

        for (Pacientes p : lista) {
            Object[] fila = {p.getCedula(), p.getNombre(), p.getApellido(), p.getTelefono()};
            modelo.addRow(fila);
        }

        // Asignar el modelo a la tabla después de agregar los datos
        tabla_tbl.setModel(modelo);
        tabla_tbl.setDefaultEditor(Object.class, null);
    }
    
    public void recargarPacientes() {
        cargarPacientesEnTabla();
    }


    private String seleccionCedu(){
        int filaSelect = tabla_tbl.getSelectedRow();
        
        if (filaSelect != -1) {
            return tabla_tbl.getValueAt(filaSelect, 0).toString(); // Obtener la cédula 
        } else {
            return null;
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Filtrotxt = new javax.swing.JTextField();
        informacion_btn = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla_tbl = new javax.swing.JTable();
        Agregar_btn = new javax.swing.JToggleButton();
        Volverbtn = new javax.swing.JToggleButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(177, 234, 242));
        jPanel1.setForeground(new java.awt.Color(177, 234, 242));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(76, 207, 225));
        jPanel2.setForeground(new java.awt.Color(76, 207, 225));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Pacientes");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(302, 302, 302))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        Filtrotxt.setBackground(new java.awt.Color(255, 255, 255));
        Filtrotxt.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Filtrotxt.setForeground(new java.awt.Color(76, 207, 225));
        Filtrotxt.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Filtrotxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                FiltrotxtKeyReleased(evt);
            }
        });
        jPanel1.add(Filtrotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, 160, 30));

        informacion_btn.setBackground(new java.awt.Color(255, 255, 255));
        informacion_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        informacion_btn.setForeground(new java.awt.Color(76, 207, 225));
        informacion_btn.setText("INFORMACIÓN");
        informacion_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        informacion_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacion_btnActionPerformed(evt);
            }
        });
        jPanel1.add(informacion_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 130, 30));

        tabla_tbl.setBackground(new java.awt.Color(255, 255, 255));
        tabla_tbl.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        tabla_tbl.setForeground(new java.awt.Color(76, 207, 225));
        tabla_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla_tbl);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 760, 370));

        Agregar_btn.setBackground(new java.awt.Color(255, 255, 255));
        Agregar_btn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Agregar_btn.setForeground(new java.awt.Color(76, 207, 225));
        Agregar_btn.setText("AGREGAR PACIENTE");
        Agregar_btn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Agregar_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Agregar_btnActionPerformed(evt);
            }
        });
        jPanel1.add(Agregar_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, 150, 30));

        Volverbtn.setBackground(new java.awt.Color(255, 255, 255));
        Volverbtn.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Volverbtn.setForeground(new java.awt.Color(76, 207, 225));
        Volverbtn.setText("VOLVER");
        Volverbtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Volverbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverbtnActionPerformed(evt);
            }
        });
        jPanel1.add(Volverbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 540, 90, 30));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CEDULA:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 70, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void informacion_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacion_btnActionPerformed
        String selectedCedu = seleccionCedu();
        
        if (selectedCedu != null) {
            Agregar_Paciente ventana = new Agregar_Paciente(selectedCedu, this);
            this.dispose();
            ventana.setVisible(true);
            ventana.pack();
            ventana.setLocationRelativeTo(null);
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un paciente de la lista.");
        }
    }//GEN-LAST:event_informacion_btnActionPerformed

    private void Agregar_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Agregar_btnActionPerformed
        Agregar_Paciente agregar = new Agregar_Paciente();
        this.dispose();
        agregar.setVisible(true);
        agregar.pack();
        agregar.setLocationRelativeTo(null);
    }//GEN-LAST:event_Agregar_btnActionPerformed

    private void VolverbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverbtnActionPerformed
        Menu_Principal mp = new Menu_Principal();
        this.dispose();
        mp.setVisible(true);
        mp.pack();
        mp.setLocationRelativeTo(null);
    }//GEN-LAST:event_VolverbtnActionPerformed

    private void FiltrotxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_FiltrotxtKeyReleased
        DefaultTableModel ob = (DefaultTableModel) tabla_tbl.getModel();
        TableRowSorter<DefaultTableModel> obj = new TableRowSorter<>(ob);
        tabla_tbl.setRowSorter(obj);

        String filtro = Filtrotxt.getText();
        // Filtrar solo por la columna 0 (donde está la cédula)
        RowFilter<DefaultTableModel, Object> rf = RowFilter.regexFilter("^" + filtro, 0); 
        obj.setRowFilter(rf);
    }//GEN-LAST:event_FiltrotxtKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listaPacientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new listaPacientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JToggleButton Agregar_btn;
    public javax.swing.JTextField Filtrotxt;
    public javax.swing.JToggleButton Volverbtn;
    public javax.swing.JToggleButton informacion_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable tabla_tbl;
    // End of variables declaration//GEN-END:variables
}
