/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import conexion.DAOlogin;
import conexion.conexionSQL;
import java.sql.Connection;
import javax.swing.JOptionPane;

public class Login extends javax.swing.JFrame {

    conexionSQL con = new conexionSQL();
    Connection cn = con.conectar();    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        pack();
        setLocationRelativeTo(null);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PL_BASE = new javax.swing.JPanel();
        PL_izquierda = new javax.swing.JPanel();
        Label_imagen = new javax.swing.JLabel();
        PL_derecha = new javax.swing.JPanel();
        TXT_usuario = new javax.swing.JTextField();
        TXT_clave = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        BTN_entrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PL_BASE.setBackground(new java.awt.Color(0, 0, 0));
        PL_BASE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PL_izquierda.setBackground(new java.awt.Color(255, 255, 255));

        Label_imagen.setForeground(new java.awt.Color(0, 0, 0));
        Label_imagen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/images.png"))); // NOI18N

        javax.swing.GroupLayout PL_izquierdaLayout = new javax.swing.GroupLayout(PL_izquierda);
        PL_izquierda.setLayout(PL_izquierdaLayout);
        PL_izquierdaLayout.setHorizontalGroup(
            PL_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PL_izquierdaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(Label_imagen)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        PL_izquierdaLayout.setVerticalGroup(
            PL_izquierdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PL_izquierdaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(Label_imagen)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        PL_BASE.add(PL_izquierda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 360));

        PL_derecha.setBackground(new java.awt.Color(55, 135, 25));

        TXT_usuario.setBackground(new java.awt.Color(255, 255, 255));
        TXT_usuario.setForeground(new java.awt.Color(102, 102, 102));
        TXT_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TXT_usuarioActionPerformed(evt);
            }
        });

        TXT_clave.setBackground(new java.awt.Color(255, 255, 255));
        TXT_clave.setForeground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("MediTrack v0.03");

        BTN_entrar.setBackground(new java.awt.Color(255, 255, 255));
        BTN_entrar.setForeground(new java.awt.Color(0, 0, 0));
        BTN_entrar.setText("Entrar");
        BTN_entrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_entrarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Usuario:");

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Contraseña:");

        javax.swing.GroupLayout PL_derechaLayout = new javax.swing.GroupLayout(PL_derecha);
        PL_derecha.setLayout(PL_derechaLayout);
        PL_derechaLayout.setHorizontalGroup(
            PL_derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PL_derechaLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(PL_derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TXT_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TXT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(145, 145, 145))
            .addGroup(PL_derechaLayout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(BTN_entrar, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PL_derechaLayout.setVerticalGroup(
            PL_derechaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PL_derechaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(47, 47, 47)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TXT_clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(BTN_entrar)
                .addGap(39, 39, 39))
        );

        PL_BASE.add(PL_derecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 0, 580, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PL_BASE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PL_BASE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TXT_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TXT_usuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TXT_usuarioActionPerformed

    private void BTN_entrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_entrarActionPerformed
        DAOlogin dao = new DAOlogin(cn);
        
        String usuario = TXT_usuario.getText();
        String clave = new String(TXT_clave.getPassword());
        
        boolean verificacion = dao.ValidarUsuario(usuario, clave);
        
        if(verificacion == true){
            Menu_Principal mp = new Menu_Principal();
            mp.setVisible(verificacion);
            mp.pack();
            mp.setLocationRelativeTo(null);
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "El usuario indicado no existe \nPor favor intente nuevamente");
        }
    }//GEN-LAST:event_BTN_entrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton BTN_entrar;
    private javax.swing.JLabel Label_imagen;
    private javax.swing.JPanel PL_BASE;
    private javax.swing.JPanel PL_derecha;
    private javax.swing.JPanel PL_izquierda;
    private javax.swing.JPasswordField TXT_clave;
    private javax.swing.JTextField TXT_usuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
