/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaces;

import Imagenes.PDF;
import conexion.conexionSQL;
import java.sql.Connection;

/**
 *
 * @author Burrx
 */
public class Menu_Principal extends javax.swing.JFrame {
    conexionSQL con = new conexionSQL();
    Connection cn = con.conectar();
    /**
     * Creates new form Menu_Principal
     */
    public Menu_Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTN_paciente = new javax.swing.JButton();
        BTN_consulta = new javax.swing.JButton();
        BTN_Agenda = new javax.swing.JButton();
        BTN_listaRecipes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(177, 234, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Medicontrol");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Dr: XXXXXXXXXXXXXXXXXXXXXXXXXXX");

        BTN_paciente.setBackground(new java.awt.Color(76, 207, 225));
        BTN_paciente.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        BTN_paciente.setForeground(new java.awt.Color(255, 255, 255));
        BTN_paciente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Copilot_20250627_193612.png"))); // NOI18N
        BTN_paciente.setText("Nuevo Paciente");
        BTN_paciente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BTN_paciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_pacienteActionPerformed(evt);
            }
        });

        BTN_consulta.setBackground(new java.awt.Color(76, 207, 225));
        BTN_consulta.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        BTN_consulta.setForeground(new java.awt.Color(255, 255, 255));
        BTN_consulta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Copilot_20250627_192525.png"))); // NOI18N
        BTN_consulta.setText("Consulta");
        BTN_consulta.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BTN_consulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_consultaActionPerformed(evt);
            }
        });

        BTN_Agenda.setBackground(new java.awt.Color(76, 207, 225));
        BTN_Agenda.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        BTN_Agenda.setForeground(new java.awt.Color(255, 255, 255));
        BTN_Agenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Copilot_20250627_190123.png"))); // NOI18N
        BTN_Agenda.setText("Agenda");
        BTN_Agenda.setHorizontalTextPosition(javax.swing.SwingConstants.LEADING);
        BTN_Agenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_AgendaActionPerformed(evt);
            }
        });

        BTN_listaRecipes.setBackground(new java.awt.Color(76, 207, 225));
        BTN_listaRecipes.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        BTN_listaRecipes.setForeground(new java.awt.Color(255, 255, 255));
        BTN_listaRecipes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Copilot_20250627_194527.png"))); // NOI18N
        BTN_listaRecipes.setText("Lista recipes");
        BTN_listaRecipes.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        BTN_listaRecipes.setIconTextGap(0);
        BTN_listaRecipes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_listaRecipesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BTN_paciente, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 318, Short.MAX_VALUE)
                        .addComponent(BTN_listaRecipes, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(BTN_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BTN_Agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(515, 515, 515))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(470, 470, 470))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN_paciente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_listaRecipes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN_consulta, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN_Agenda, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1300, 750));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTN_pacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_pacienteActionPerformed
        listaPacientes lp = new listaPacientes();
        this.dispose();
        lp.setVisible(true);
        lp.pack();
        lp.setLocationRelativeTo(null);
    }//GEN-LAST:event_BTN_pacienteActionPerformed

    private void BTN_consultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_consultaActionPerformed
        Pagina_Consultas pc = new Pagina_Consultas();
        this.dispose();
        pc.setVisible(true);
        pc.pack();
        pc.setLocationRelativeTo(null);
    }//GEN-LAST:event_BTN_consultaActionPerformed

    private void BTN_AgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_AgendaActionPerformed
        agenda ag = new agenda();
        this.dispose();
        ag.setVisible(true);
        ag.pack();
        ag.setLocationRelativeTo(null);
    }//GEN-LAST:event_BTN_AgendaActionPerformed

    private void BTN_listaRecipesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_listaRecipesActionPerformed
        Lista_Recipes LR = new Lista_Recipes();
        this.dispose();
        LR.setVisible(true);
        LR.pack();
        LR.setLocationRelativeTo(null);
    }//GEN-LAST:event_BTN_listaRecipesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Agenda;
    private javax.swing.JButton BTN_consulta;
    private javax.swing.JButton BTN_listaRecipes;
    public javax.swing.JButton BTN_paciente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
